# Generated by Django 5.2.14 on 2026-05-27 19:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Gold", "Gold"),
                            ("Silver", "Silver"),
                            ("Platinum", "Platinum"),
                            ("Gemstones", "Gemstones"),
                            ("Chemicals", "Chemicals"),
                            ("Tools", "Tools"),
                            ("Packaging", "Packaging"),
                        ],
                        max_length=100,
                        unique=True,
                        verbose_name="Category Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Material Category",
                "verbose_name_plural": "Material Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Supplier Name"),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Contact Person"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="Phone"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Address")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RawMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Material Name"),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        choices=[
                            ("grams", "Grams"),
                            ("carats", "Carats"),
                            ("pieces", "Pieces"),
                            ("liters", "Liters"),
                            ("kg", "Kilograms"),
                        ],
                        default="grams",
                        max_length=20,
                        verbose_name="Unit of Measure",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "minimum_stock_level",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Alert is raised when stock falls below this level.",
                        max_digits=12,
                        verbose_name="Minimum Stock Level",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materials",
                        to="inventory.materialcategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Raw Material",
                "verbose_name_plural": "Raw Materials",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="CurrentStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_on_hand",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                        verbose_name="Quantity on Hand",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "material",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_stock",
                        to="inventory.rawmaterial",
                        verbose_name="Material",
                    ),
                ),
            ],
            options={
                "verbose_name": "Current Stock",
                "verbose_name_plural": "Current Stocks",
            },
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("IN", "Stock In"),
                            ("OUT", "Stock Out"),
                            ("ADJUSTMENT", "Adjustment"),
                            ("WASTE", "Waste"),
                        ],
                        max_length=20,
                        verbose_name="Transaction Type",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Use positive values; direction is determined by transaction_type.",
                        max_digits=12,
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Reference Number"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "job_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_transactions",
                        to="orders.joborder",
                        verbose_name="Job Order",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="inventory.rawmaterial",
                        verbose_name="Material",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Transaction",
                "verbose_name_plural": "Stock Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="Quantity"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Cost per unit of measure.",
                        max_digits=12,
                        verbose_name="Unit Cost",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=4,
                        editable=False,
                        max_digits=16,
                        verbose_name="Total Cost",
                    ),
                ),
                (
                    "entry_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Entry Date"
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Batch Number"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "purity",
                    models.CharField(
                        blank=True,
                        help_text="For gold/silver: e.g. 18k, 22k, 24k, 925, 999.",
                        max_length=20,
                        verbose_name="Purity",
                    ),
                ),
                (
                    "is_bulk",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates this entry was created via bulk CSV upload.",
                        verbose_name="Bulk Entry",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Entered By",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_entries",
                        to="inventory.rawmaterial",
                        verbose_name="Material",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_entries",
                        to="inventory.supplier",
                        verbose_name="Supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Entry",
                "verbose_name_plural": "Stock Entries",
                "ordering": ["-entry_date", "-id"],
            },
        ),
    ]
