# Generated by Django 5.2.14 on 2026-05-27 19:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Stage Name")),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("DESIGN", "Design & Specification"),
                            ("WAX_CARVING", "Wax Carving / CAD Modeling"),
                            ("INVESTMENT", "Investment & Burnout"),
                            ("CASTING", "Metal Casting"),
                            ("FILING", "Filing & Sprue Removal"),
                            ("POLISHING", "Polishing & Cleaning"),
                            ("STONE_SETTING", "Stone Setting"),
                            ("QUALITY_CHECK", "Quality Control Check"),
                            ("PLATING", "Plating & Finishing"),
                            ("FINAL_INSPECTION", "Final Inspection"),
                            ("PACKAGING", "Packaging & Delivery Ready"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Stage Code",
                    ),
                ),
                (
                    "order_number",
                    models.PositiveIntegerField(
                        help_text="Defines the sequence of stages in the manufacturing workflow.",
                        unique=True,
                        verbose_name="Order Number",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Process Stage",
                "verbose_name_plural": "Process Stages",
                "ordering": ["order_number"],
            },
        ),
        migrations.CreateModel(
            name="ProductionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_number",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated in format PJ-YYYY-NNNN.",
                        max_length=20,
                        unique=True,
                        verbose_name="Job Number",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "target_completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Target Completion Date"
                    ),
                ),
                (
                    "actual_completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Actual Completion Date"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_jobs_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "current_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_jobs",
                        to="manufacturing.processstage",
                        verbose_name="Current Stage",
                    ),
                ),
                (
                    "job_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_jobs",
                        to="orders.joborder",
                        verbose_name="Job Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Production Job",
                "verbose_name_plural": "Production Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started At"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "weight_in",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Weight of piece entering this stage, in grams.",
                        max_digits=10,
                        null=True,
                        verbose_name="Weight In (g)",
                    ),
                ),
                (
                    "weight_out",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Weight of piece leaving this stage, in grams.",
                        max_digits=10,
                        null=True,
                        verbose_name="Weight Out (g)",
                    ),
                ),
                (
                    "waste_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Measured waste/scrap generated at this stage, in grams.",
                        max_digits=10,
                        null=True,
                        verbose_name="Waste Weight (g)",
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="Remarks")),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="process_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned To",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="process_records",
                        to="manufacturing.processstage",
                        verbose_name="Stage",
                    ),
                ),
                (
                    "production_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_records",
                        to="manufacturing.productionjob",
                        verbose_name="Production Job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Process Record",
                "verbose_name_plural": "Process Records",
                "ordering": ["production_job", "stage__order_number"],
                "unique_together": {("production_job", "stage")},
            },
        ),
        migrations.CreateModel(
            name="MaterialIssuance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_requested",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        verbose_name="Quantity Requested",
                    ),
                ),
                (
                    "quantity_issued",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="Quantity Issued"
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Issued At"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "issued_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_issuances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Issued By",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_issuances",
                        to="inventory.rawmaterial",
                        verbose_name="Material",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_issuances",
                        to="manufacturing.processstage",
                        verbose_name="Stage",
                    ),
                ),
                (
                    "production_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_issuances",
                        to="manufacturing.productionjob",
                        verbose_name="Production Job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material Issuance",
                "verbose_name_plural": "Material Issuances",
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="QualityCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Checked At"
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("CONDITIONAL", "Conditional"),
                        ],
                        max_length=20,
                        verbose_name="Result",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Weight (g)",
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 25mm x 15mm x 3mm",
                        max_length=200,
                        verbose_name="Dimensions",
                    ),
                ),
                (
                    "finish_grade",
                    models.CharField(
                        choices=[
                            ("A", "Grade A"),
                            ("B", "Grade B"),
                            ("C", "Grade C"),
                            ("REJECT", "Reject"),
                        ],
                        max_length=10,
                        verbose_name="Finish Grade",
                    ),
                ),
                (
                    "defects_found",
                    models.TextField(blank=True, verbose_name="Defects Found"),
                ),
                (
                    "corrective_action",
                    models.TextField(blank=True, verbose_name="Corrective Action"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_checks_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quality_checks_performed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Checked By",
                    ),
                ),
                (
                    "process_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_checks",
                        to="manufacturing.processrecord",
                        verbose_name="Process Record",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quality Check",
                "verbose_name_plural": "Quality Checks",
                "ordering": ["-checked_at"],
            },
        ),
    ]
